import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { useEagerConnect } from '../../src/hooks/useEgerConnect'
import { useWalletModal } from '../../src/hooks/useWalletModal'
import { useWalletProvider } from '../../src/hooks/useWalletProvider'
import { useState } from 'react'

export default function Home() {
  const [eagerConnect, setEagerConnect] = useState(false)

  useEagerConnect(eagerConnect)
  const { setOpen, deactivate, error: walletError } = useWalletModal()
  const { account, connected } = useWalletProvider()

  return (
    <div className={styles.container}>
      <Head>
        <title>Blockchain Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Wallet Modal Test</h2>
        <button onClick={() => (connected ? deactivate() : setOpen(true))}>
          {connected ? 'Disconnect' : 'Connect'}
        </button>
        <br />
        <button onClick={() => setEagerConnect(!eagerConnect)}>
          {eagerConnect ? 'Disable Eager Connect' : 'Enable Eager Connect'}
        </button>
        <p>{connected && account}</p>
        <p style={{ color: 'red' }}>{walletError && walletError}</p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <h2>skyxcripto</h2>
          </span>
        </a>
      </footer>
    </div>
  )
}
